// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6hcszVvgjR_3jZ8bhtIL-lnMO9e92XgE',
    appId: '1:525692480911:web:ff6d9747864a487603effa',
    messagingSenderId: '525692480911',
    projectId: 'lakshya-e0ed8',
    authDomain: 'lakshya-e0ed8.firebaseapp.com',
    storageBucket: 'lakshya-e0ed8.appspot.com',
    measurementId: 'G-3WRYTQZ7S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE0iz7XkAQPjnq39yT7mKP1xYGM66TM2w',
    appId: '1:525692480911:android:4a7fcf4669627b8e03effa',
    messagingSenderId: '525692480911',
    projectId: 'lakshya-e0ed8',
    storageBucket: 'lakshya-e0ed8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcUDa8AtpDFoZYVwWUUMfEkT5hnssRK6g',
    appId: '1:525692480911:ios:1ed46fbdfcb5d7d603effa',
    messagingSenderId: '525692480911',
    projectId: 'lakshya-e0ed8',
    storageBucket: 'lakshya-e0ed8.appspot.com',
    iosBundleId: 'com.example.lakshya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcUDa8AtpDFoZYVwWUUMfEkT5hnssRK6g',
    appId: '1:525692480911:ios:1ed46fbdfcb5d7d603effa',
    messagingSenderId: '525692480911',
    projectId: 'lakshya-e0ed8',
    storageBucket: 'lakshya-e0ed8.appspot.com',
    iosBundleId: 'com.example.lakshya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6hcszVvgjR_3jZ8bhtIL-lnMO9e92XgE',
    appId: '1:525692480911:web:c36f438961800cd403effa',
    messagingSenderId: '525692480911',
    projectId: 'lakshya-e0ed8',
    authDomain: 'lakshya-e0ed8.firebaseapp.com',
    storageBucket: 'lakshya-e0ed8.appspot.com',
    measurementId: 'G-XK8400JR76',
  );
}
